<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.663"/>
    <xacro:property name="base_width" value="0.568"/>
    <xacro:property name="base_height" value="0.682"/>
    <xacro:property name="clearance" value="0.05"/>
    <xacro:property name="mass" value="60.0"/> 

    <xacro:property name="ixx" value="${mass * (base_width**2 + base_height**2) / 12}"/>
    <xacro:property name="iyy" value="${mass * (base_length**2 + base_height**2) / 12}"/>
    <xacro:property name="izz" value="${mass * (base_length**2 + base_width**2) / 12}"/>

    <xacro:macro name="base">
        <link name="base_footprint"/>

        <link name="base_link">
            <visual>
                <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="${mass}"/>
                <inertia ixx="${ixx}" ixy="0.0" ixz="0.0" 
                         iyy="${iyy}" iyz="0.0" 
                         izz="${izz}"/>
            </inertial>
        </link>

        <joint name="base_link_joint" type="fixed">
            <origin xyz="0.0 0.0 ${base_height/2 + clearance}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint"/>
            <child link="base_link"/>
        </joint>
    </xacro:macro>
</robot>